version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: insight-postgres
    environment:
      POSTGRES_DB: insight_db
      POSTGRES_USER: insight_user
      POSTGRES_PASSWORD: insight_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insight_user -d insight_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Insight Service application
  insight-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insight-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/insight_db
      - DATABASE_USER=insight_user
      - DATABASE_PASSWORD=insight_password
      - APP_ENV=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: insight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Adminer - Database management UI (optional)
  adminer:
    image: adminer:latest
    container_name: insight-adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local