{{- if .Values.syncService.enabled }}
# Service
{{- $serviceContext := dict "root" . "serviceName" "sync-service" "serviceConfig" .Values.syncService }}
{{- include "vertex.service" $serviceContext }}
---
# Deployment
{{- $deploymentContext := dict "root" . "serviceName" "sync-service" "serviceConfig" .Values.syncService "dbName" "vertex_sync" "extraEnv" nil }}
{{- include "vertex.deployment" $deploymentContext }}
---
# HorizontalPodAutoscaler
{{- $hpaContext := dict "root" . "serviceName" "sync-service" "serviceConfig" .Values.syncService }}
{{- include "vertex.hpa" $hpaContext }}
---
# NetworkPolicy
{{- $networkContext := dict "root" . "serviceName" "sync-service" "extraEgress" nil }}
{{- include "vertex.networkpolicy" $networkContext }}
---
# PodDisruptionBudget
{{- $pdbContext := dict "root" . "serviceName" "sync-service" }}
{{- include "vertex.pdb" $pdbContext }}
{{- end }}