version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: eden
      POSTGRES_USER: eden
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eden -d eden"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eden Single Binary - All Services
  eden:
    build: .
    ports:
      - "8000:8000"  # API Gateway
      - "8080:8080"  # Vault
      - "8081:8081"  # Flow
      - "8082:8082"  # Task
      - "8083:8083"  # Monitor
      - "8084:8084"  # Sync
      - "8085:8085"  # Insight
      - "8086:8086"  # Hub
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: eden
      DB_USER: eden
      DB_PASSWORD: secret
      DB_SSL_MODE: disable
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "./eden", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
