global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true
  slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-eden-email'
  routes:
  - match:
      severity: critical
    receiver: 'team-eden-pager'
    continue: true
  - match:
      severity: warning
    receiver: 'team-eden-slack'
    continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'team-eden-email'
    email_configs:
    - to: 'team@example.com'
      send_resolved: true

  - name: 'team-eden-pager'
    pagerduty_configs:
    - service_key: '<pagerduty-service-key>'
      send_resolved: true

  - name: 'team-eden-slack'
    slack_configs:
    - channel: '#eden-alerts'
      send_resolved: true
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Details:*
          {{ range .Labels.SortedPairs }}
            • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}