# Values for Azure AKS environment

global:
  environment: production
  image:
    repository: ${ACR_NAME}.azurecr.io/eden
    tag: latest
    pullPolicy: Always
  
  # Production resources
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  # Database settings for Azure Database for PostgreSQL
  database:
    host: eden-postgres.postgres.database.azure.com
    port: 5432
    user: postgres@eden-postgres
    # Password should be provided via Azure Key Vault
    password: ${DB_PASSWORD}
    sslMode: require
  
  # Enable network policies for production
  networkPolicy:
    enabled: true
  
  # Enable PDB for production
  pdb:
    enabled: true
    minAvailable: 1

  # Security settings
  security:
    jwtSecret: ${JWT_SECRET}
    encryptionKey: ${ENCRYPTION_KEY}

# Use external Azure Database for PostgreSQL
postgresql:
  enabled: false

# Use Azure Cache for Redis
redis:
  enabled: false
  # External Redis configuration
  external:
    host: eden-redis.redis.cache.windows.net
    port: 6380
    ssl: true

# Use Azure Monitor
prometheus:
  enabled: false

# Use Azure Monitor
grafana:
  enabled: false

# Service configurations
apiGateway:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

vaultService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

hubService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

flowService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

taskService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

monitorService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

syncService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

insightService:
  enabled: true
  replicaCount: 2
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

webUi:
  enabled: true
  replicaCount: 2
  image:
    repository: ${ACR_NAME}.azurecr.io/eden-web
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# Enable ingress with Azure Application Gateway
ingress:
  enabled: true
  className: azure-application-gateway
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
  hosts:
    - host: eden.example.com
      paths:
        - path: /
          pathType: Prefix
          service: web-ui
          port: 80
        - path: /api
          pathType: Prefix
          service: api-gateway
          port: 8080
  tls:
    - secretName: eden-tls
      hosts:
        - eden.example.com