apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - api-gateway.yaml
  - vault-service.yaml
  - hub-service.yaml
  - flow-service.yaml
  - task-service.yaml
  - monitor-service.yaml
  - sync-service.yaml
  - insight-service.yaml
  - insight-service-hpa.yaml
  - web-ui.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: eden-devops-suite
  app.kubernetes.io/managed-by: kustomize

namespace: eden