apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: eden
  labels:
    app: vault-service
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: vault-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-service
  namespace: eden
  labels:
    app: vault-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vault-service
        tier: backend
    spec:
      containers:
      - name: vault-service
        image: ataivadev/eden:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/eden_vault"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: eden-config
              key: LOG_LEVEL
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: ENCRYPTION_KEY
        - name: API_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: eden-config
              key: API_GATEWAY_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: POSTGRES_PASSWORD
        # External Secrets Manager Configuration
        - name: SECRETS_MANAGER_TYPE
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: SECRETS_MANAGER_TYPE
              optional: true
        # HashiCorp Vault Configuration
        - name: VAULT_URL
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: VAULT_URL
              optional: true
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: VAULT_TOKEN
              optional: true
        - name: VAULT_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: VAULT_NAMESPACE
              optional: true
        # AWS Secrets Manager Configuration
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: AWS_REGION
              optional: true
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: AWS_ACCESS_KEY
              optional: true
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: AWS_SECRET_KEY
              optional: true
        - name: AWS_SECRETS_PREFIX
          valueFrom:
            secretKeyRef:
              name: eden-secrets
              key: AWS_SECRETS_PREFIX
              optional: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vault-service-hpa
  namespace: eden
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vault-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-service-network-policy
  namespace: eden
spec:
  podSelector:
    matchLabels:
      app: vault-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379