name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: vertex
          POSTGRES_DB: vertex
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -short -v ./...
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: vertex
        DB_USER: vertex
        DB_PASSWORD: secret
        REDIS_HOST: localhost
        REDIS_PORT: 6379
    
    - name: Set version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o vertex-linux-amd64 ./cmd/vertex/
        GOOS=linux GOARCH=arm64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o vertex-linux-arm64 ./cmd/vertex/
        GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o vertex-darwin-amd64 ./cmd/vertex/
        GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o vertex-darwin-arm64 ./cmd/vertex/
        GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o vertex-windows-amd64.exe ./cmd/vertex/
    
    - name: Create release notes
      run: |
        cat > release-notes.md << 'EOF'
        # Vertex DevOps Suite ${{ steps.version.outputs.version }}
        
        ## Features
        - **8 Integrated Services** - Complete DevOps platform in a single binary
        - **Zero-Knowledge Secrets** - AES-256-GCM encryption with client-side security
        - **Workflow Automation** - Visual workflow designer with event-driven execution
        - **Multi-Cloud Support** - AWS, GCP, Azure, and Kubernetes integration
        - **Real-time Monitoring** - AI-powered anomaly detection and alerting
        - **Single Binary** - 19MB executable with all services included
        
        ## Core Services
        - **Vault** (Port 8080) - Secrets management with zero-knowledge architecture
        - **Flow** (Port 8081) - Workflow automation and orchestration
        - **Task** (Port 8082) - Distributed task processing and scheduling
        - **Monitor** (Port 8083) - Real-time monitoring and alerting
        - **Sync** (Port 8084) - Multi-cloud data synchronization
        - **Insight** (Port 8085) - Analytics and business intelligence
        - **Hub** (Port 8086) - Service discovery and integration
        - **API Gateway** (Port 8000) - Unified API entry point
        
        ## Installation
        
        ### Download Binary
        Download the appropriate binary for your platform from the assets below:
        
        **Linux (x64)**
        ```bash
        curl -L -o vertex https://github.com/ataiva-software/vertex/releases/download/${{ steps.version.outputs.version }}/vertex-linux-amd64
        chmod +x vertex
        sudo mv vertex /usr/local/bin/
        ```
        
        **Linux (ARM64)**
        ```bash
        curl -L -o vertex https://github.com/ataiva-software/vertex/releases/download/${{ steps.version.outputs.version }}/vertex-linux-arm64
        chmod +x vertex
        sudo mv vertex /usr/local/bin/
        ```
        
        **macOS (Intel)**
        ```bash
        curl -L -o vertex https://github.com/ataiva-software/vertex/releases/download/${{ steps.version.outputs.version }}/vertex-darwin-amd64
        chmod +x vertex
        sudo mv vertex /usr/local/bin/
        ```
        
        **macOS (Apple Silicon)**
        ```bash
        curl -L -o vertex https://github.com/ataiva-software/vertex/releases/download/${{ steps.version.outputs.version }}/vertex-darwin-arm64
        chmod +x vertex
        sudo mv vertex /usr/local/bin/
        ```
        
        **Windows**
        Download `vertex-windows-amd64.exe` and add to your PATH.
        
        ### Install with Go
        ```bash
        go install github.com/ataiva-software/vertex/cmd/vertex@${{ steps.version.outputs.version }}
        ```
        
        ## Quick Start
        
        ```bash
        # Start dependencies (PostgreSQL + Redis)
        docker run -d --name postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=vertex -e POSTGRES_DB=vertex -p 5432:5432 postgres:15
        docker run -d --name redis -p 6379:6379 redis:7
        
        # Start all Vertex services
        vertex server
        
        # Use Vertex CLI
        vertex vault store my-secret "hello world"
        vertex vault get my-secret
        vertex status
        ```
        
        ## Docker Deployment
        
        ```bash
        # Using Docker Compose
        curl -L -o docker-compose.yml https://raw.githubusercontent.com/ataiva-software/vertex/${{ steps.version.outputs.version }}/docker-compose.yml
        docker-compose up -d
        ```
        
        ## Documentation
        - [Quick Start Guide](https://github.com/ataiva-software/vertex/blob/main/docs/getting-started/quick-start.md)
        - [CLI Reference](https://github.com/ataiva-software/vertex/blob/main/docs/user-guide/cli-reference.md)
        - [Architecture Overview](https://github.com/ataiva-software/vertex/blob/main/docs/architecture/overview.md)
        - [Security Guide](https://github.com/ataiva-software/vertex/blob/main/docs/security/security-guide.md)
        EOF
    
    - name: Create or update tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
        git push origin ${{ steps.version.outputs.version }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Vertex DevOps Suite ${{ steps.version.outputs.version }}
        body_path: release-notes.md
        files: |
          vertex-linux-amd64
          vertex-linux-arm64
          vertex-darwin-amd64
          vertex-darwin-arm64
          vertex-windows-amd64.exe
        draft: false
        prerelease: false
